# Intermediate Neural Network in Tensorflow

#### Load Dependencies

In [3]:
import tensorflow
from tensorflow.keras.datasets import mnist
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Dropout, BatchNormalization
from tensorflow.keras.optimizers import SGD
from matplotlib import pyplot as plt
import numpy as np

Load Data

In [4]:
(x_train, y_train), (x_valid, y_valid) = mnist.load_data()

11490434/11490434 [==============================] - 0s 0us/step


#### Preprocess data

In [5]:
x_train = x_train.reshape(60000, 784).astype('float32')
x_valid = x_valid.reshape(10000, 784).astype('float32')

In [6]:
x_train /= 255
x_valid /= 255

In [7]:
n_classes = 10
y_train = to_categorical(y_train, n_classes)
y_valid = to_categorical(y_valid, n_classes)

Design NN architecture

In [10]:
model = Sequential()

#first hidden layer:
model.add(Dense(64, activation='relu', input_shape=(784,)))
model.add(BatchNormalization())

#second hidden layer:
model.add(Dense(128, activation='relu'))
model.add(BatchNormalization())

#third hidden layer:
model.add(Dense(64, activation='relu'))
model.add(BatchNormalization())
model.add(Dropout(0.2))

#output layer:
model.add(Dense(10, activation='softmax'))

In [11]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_2 (Dense)             (None, 64)                50240     
                                                                 
 batch_normalization (BatchN  (None, 64)               256       
 ormalization)                                                   
                                                                 
 dense_3 (Dense)             (None, 128)               8320      
                                                                 
 batch_normalization_1 (Batc  (None, 128)              512       
 hNormalization)                                                 
                                                                 
 dense_4 (Dense)             (None, 64)                8256      
                                                                 
 batch_normalization_2 (Batc  (None, 64)              


#### Compile Model



In [12]:
model.compile(loss='categorical_crossentropy', optimizer='nadam', metrics=('accuracy'))

#### Train Model

In [13]:
model.fit(x_train, y_train, batch_size=128, epochs=10, verbose=1, validation_data=(x_valid, y_valid))

Epoch 1/10
469/469 [==============================] - 6s 7ms/step - loss: 0.3714 - accuracy: 0.8899 - val_loss: 0.1521 - val_accuracy: 0.9514
Epoch 2/10
469/469 [==============================] - 2s 5ms/step - loss: 0.1442 - accuracy: 0.9564 - val_loss: 0.1066 - val_accuracy: 0.9661
Epoch 3/10
469/469 [==============================] - 2s 5ms/step - loss: 0.1054 - accuracy: 0.9674 - val_loss: 0.0928 - val_accuracy: 0.9699
Epoch 4/10
469/469 [==============================] - 2s 5ms/step - loss: 0.0842 - accuracy: 0.9740 - val_loss: 0.0851 - val_accuracy: 0.9734
Epoch 5/10
469/469 [==============================] - 2s 5ms/step - loss: 0.0688 - accuracy: 0.9782 - val_loss: 0.0825 - val_accuracy: 0.9744
Epoch 6/10
469/469 [==============================] - 3s 6ms/step - loss: 0.0608 - accuracy: 0.9806 - val_loss: 0.0928 - val_accuracy: 0.9717
Epoch 7/10
469/469 [==============================] - 2s 5ms/step - loss: 0.0502 - accuracy: 0.9842 - val_loss: 0.0834 - val_accuracy: 0.9753
Epoch 

#### Evaluating Model Performance

In [14]:
model.evaluate(x_valid, y_valid)

313/313 [==============================] - 0s 1ms/step - loss: 0.0812 - accuracy: 0.9758


[0.08119715005159378, 0.9757999777793884]

#### Performing inference

In [15]:
valid_0 = x_valid[0].reshape(1, 784)

In [16]:
y_valid[0]

array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0.], dtype=float32)

In [17]:
model.predict(valid_0)

1/1 [==============================] - 0s 114ms/step


array([[2.1927185e-06, 5.6375711e-06, 5.8901151e-06, 1.3532829e-04,
        5.6916326e-07, 2.6502687e-06, 3.3290384e-08, 9.9982965e-01,
        1.5322511e-06, 1.6450345e-05]], dtype=float32)

In [18]:
np.argmax(model.predict(valid_0), axis=-1)

1/1 [==============================] - 0s 18ms/step


array([7])