# Intermediate Neural Network in Tensorflow

#### Load Dependencies

In [1]:
import tensorflow
from tensorflow.keras.datasets import mnist
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import SGD
from matplotlib import pyplot as plt
import numpy as np

Load Data

In [2]:
(x_train, y_train), (x_valid, y_valid) = mnist.load_data()

11490434/11490434 [==============================] - 1s 0us/step


#### Preprocess data

In [6]:
x_train = x_train.reshape(60000, 784).astype('float32')
x_valid = x_valid.reshape(10000, 784).astype('float32')

In [7]:
x_train /= 255
x_valid /= 255

In [8]:
n_classes = 10
y_train = to_categorical(y_train, n_classes)
y_valid = to_categorical(y_valid, n_classes)

Design NN architecture

In [9]:
model = Sequential()

#hidden layer:
model.add(Dense(64, activation='relu', input_shape=(784,)))
model.add(Dense(128, activation='relu'))
#output layer:
model.add(Dense(10, activation='softmax'))

In [10]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 64)                50240     
                                                                 
 dense_1 (Dense)             (None, 128)               8320      
                                                                 
 dense_2 (Dense)             (None, 10)                1290      
                                                                 
Total params: 59,850
Trainable params: 59,850
Non-trainable params: 0
_________________________________________________________________



#### Compile Model



In [11]:
model.compile(loss='categorical_crossentropy', optimizer=SGD(learning_rate=0.1), metrics=('accuracy'))

#### Train Model

In [12]:
model.fit(x_train, y_train, batch_size=128, epochs=20, verbose=1, validation_data=(x_valid, y_valid))

Epoch 1/20
469/469 [==============================] - 3s 6ms/step - loss: 0.4913 - accuracy: 0.8602 - val_loss: 0.2751 - val_accuracy: 0.9215
Epoch 2/20
469/469 [==============================] - 2s 4ms/step - loss: 0.2349 - accuracy: 0.9306 - val_loss: 0.2034 - val_accuracy: 0.9412
Epoch 3/20
469/469 [==============================] - 2s 5ms/step - loss: 0.1802 - accuracy: 0.9464 - val_loss: 0.1658 - val_accuracy: 0.9475
Epoch 4/20
469/469 [==============================] - 2s 5ms/step - loss: 0.1489 - accuracy: 0.9568 - val_loss: 0.1596 - val_accuracy: 0.9509
Epoch 5/20
469/469 [==============================] - 3s 6ms/step - loss: 0.1277 - accuracy: 0.9619 - val_loss: 0.1470 - val_accuracy: 0.9552
Epoch 6/20
469/469 [==============================] - 2s 5ms/step - loss: 0.1109 - accuracy: 0.9672 - val_loss: 0.1134 - val_accuracy: 0.9663
Epoch 7/20
469/469 [==============================] - 2s 5ms/step - loss: 0.0989 - accuracy: 0.9701 - val_loss: 0.1162 - val_accuracy: 0.9656
Epoch 

#### Evaluating Model Performance

In [13]:
model.evaluate(x_valid, y_valid)

313/313 [==============================] - 1s 2ms/step - loss: 0.0815 - accuracy: 0.9744


[0.08152546733617783, 0.974399983882904]

#### Performing inference

In [14]:
valid_0 = x_valid[0].reshape(1, 784)

In [16]:
y_valid[0]

array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0.], dtype=float32)

In [15]:
model.predict(valid_0)

1/1 [==============================] - 0s 129ms/step


array([[6.92714508e-09, 1.55997899e-08, 1.37060797e-05, 2.38324228e-05,
        1.15348975e-09, 1.13821566e-08, 1.70890570e-15, 9.99960780e-01,
        1.63055020e-07, 1.49913433e-06]], dtype=float32)

In [ ]:
np.argmax(model.predict(valid_0), axis=-1)

1/1 [==============================] - 0s 34ms/step


array([7])