# Regression Example in Tensorflow

#### Load Dependencies

In [2]:
import numpy as np
from tensorflow.keras.datasets import boston_housing
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.layers import BatchNormalization
from tensorflow.keras.callbacks import ModelCheckpoint, TensorBoard
import os

#### Load Data

In [3]:
(x_train, y_train), (x_valid, y_valid) = boston_housing.load_data()

In [4]:
x_train.shape

(404, 13)

In [5]:
x_valid.shape

(102, 13)

In [6]:
x_train[0]

array([  1.23247,   0.     ,   8.14   ,   0.     ,   0.538  ,   6.142  ,
        91.7    ,   3.9769 ,   4.     , 307.     ,  21.     , 396.9    ,
        18.72   ])

In [7]:
y_train[0]

15.2

#### Design Neural Network Architecture

In [8]:
model = Sequential()

#first hidden layer
model.add(Dense(32, input_dim=13, activation='relu'))
model.add(BatchNormalization())

#second hidden layer
model.add(Dense(16, activation='relu'))
model.add(BatchNormalization())
model.add(Dropout(0.5))

#output Layer
model.add(Dense(1, activation='linear'))

In [9]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 32)                448       
                                                                 
 batch_normalization (BatchN  (None, 32)               128       
 ormalization)                                                   
                                                                 
 dense_1 (Dense)             (None, 16)                528       
                                                                 
 batch_normalization_1 (Batc  (None, 16)               64        
 hNormalization)                                                 
                                                                 
 dropout (Dropout)           (None, 16)                0         
                                                                 
 dense_2 (Dense)             (None, 1)                 1

#### Configure Model

In [10]:
model.compile(loss='mean_squared_error', optimizer='nadam')

In [11]:
output_dir = 'model_output/'

In [12]:
run_name = 'regression_drop50'
output_path = output_dir + run_name

In [13]:
if not os.path.exists(output_path):
  os.makedirs(output_path)

In [14]:
modelcheckpoint = ModelCheckpoint(output_path + '/weights.{epoch:02d}.hdf5', save_weights_only=True)

In [15]:
tensorboard = TensorBoard(log_dir = 'logs/' + run_name)

#### Train Model

In [16]:
model.fit(x_train, y_train,
          batch_size = 8, epochs=32, verbose=1,
          validation_data = (x_valid, y_valid),
          callbacks =  [modelcheckpoint, tensorboard])

Epoch 1/32
51/51 [==============================] - 3s 9ms/step - loss: 581.5638 - val_loss: 565.6111
Epoch 2/32
51/51 [==============================] - 0s 4ms/step - loss: 570.9958 - val_loss: 554.4988
Epoch 3/32
51/51 [==============================] - 0s 5ms/step - loss: 555.9479 - val_loss: 544.8421
Epoch 4/32
51/51 [==============================] - 0s 5ms/step - loss: 534.1643 - val_loss: 540.2019
Epoch 5/32
51/51 [==============================] - 0s 6ms/step - loss: 516.4315 - val_loss: 526.6102
Epoch 6/32
51/51 [==============================] - 0s 4ms/step - loss: 498.0510 - val_loss: 506.7386
Epoch 7/32
51/51 [==============================] - 0s 5ms/step - loss: 482.8836 - val_loss: 502.2791
Epoch 8/32
51/51 [==============================] - 0s 6ms/step - loss: 453.5139 - val_loss: 496.9796
Epoch 9/32
51/51 [==============================] - 0s 7ms/step - loss: 414.8444 - val_loss: 446.9670
Epoch 10/32
51/51 [==============================] - 0s 7ms/step - loss: 394.0599 

#### Performing Inference

In [ ]:
model.load_weights(output_path + '/weights.26.hdf5')

In [ ]:
x_valid[42]

array([  9.32909,   0.     ,  18.1    ,   0.     ,   0.713  ,   6.185  ,
        98.7    ,   2.2616 ,  24.     , 666.     ,  20.2    , 396.9    ,
        18.13   ])

In [ ]:
y_valid[42]

14.1

In [ ]:
model.predict(np.reshape(x_valid[42], [1, 13]))

1/1 [==============================] - 0s 26ms/step


array([[14.703564]], dtype=float32)