# Regression Example in Tensorflow

#### Load Dependencies

In [1]:
import numpy as np
from tensorflow.keras.datasets import boston_housing
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.layers import BatchNormalization
from tensorflow.keras.callbacks import ModelCheckpoint
import os

#### Load Data

In [2]:
(x_train, y_train), (x_valid, y_valid) = boston_housing.load_data()

In [3]:
x_train.shape

(404, 13)

In [4]:
x_valid.shape

(102, 13)

In [5]:
x_train[0]

array([  1.23247,   0.     ,   8.14   ,   0.     ,   0.538  ,   6.142  ,
        91.7    ,   3.9769 ,   4.     , 307.     ,  21.     , 396.9    ,
        18.72   ])

In [6]:
y_train[0]

15.2

#### Design Neural Network Architecture

In [7]:
model = Sequential()

#first hidden layer
model.add(Dense(32, input_dim=13, activation='relu'))
model.add(BatchNormalization())

#second hidden layer
model.add(Dense(16, activation='relu'))
model.add(BatchNormalization())
model.add(Dropout(0.2))

#output Layer
model.add(Dense(1, activation='linear'))

In [8]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 32)                448       
                                                                 
 batch_normalization (BatchN  (None, 32)               128       
 ormalization)                                                   
                                                                 
 dense_1 (Dense)             (None, 16)                528       
                                                                 
 batch_normalization_1 (Batc  (None, 16)               64        
 hNormalization)                                                 
                                                                 
 dropout (Dropout)           (None, 16)                0         
                                                                 
 dense_2 (Dense)             (None, 1)                 1

#### Configure Model

In [9]:
model.compile(loss='mean_squared_error', optimizer='nadam')

In [10]:
output_dir = 'model_output/'

In [11]:
run_name = 'regression_baseline'
output_path = output_dir + run_name

In [12]:
if not os.path.exists(output_path):
  os.makedirs(output_path)

In [13]:
modelcheckpoint = ModelCheckpoint(output_path + '/weights.{epoch:02d}.hdf5', save_weights_only=True)

#### Train Model

In [14]:
model.fit(x_train, y_train,
          batch_size = 8, epochs=32, verbose=1,
          validation_data = (x_valid, y_valid),
          callbacks =  [modelcheckpoint])

Epoch 1/32
51/51 [==============================] - 5s 9ms/step - loss: 574.5326 - val_loss: 428.8710
Epoch 2/32
51/51 [==============================] - 0s 4ms/step - loss: 553.7610 - val_loss: 471.5338
Epoch 3/32
51/51 [==============================] - 0s 4ms/step - loss: 537.0491 - val_loss: 473.4468
Epoch 4/32
51/51 [==============================] - 0s 4ms/step - loss: 513.6149 - val_loss: 474.2557
Epoch 5/32
51/51 [==============================] - 0s 3ms/step - loss: 491.6706 - val_loss: 444.0755
Epoch 6/32
51/51 [==============================] - 0s 4ms/step - loss: 457.4970 - val_loss: 487.1745
Epoch 7/32
51/51 [==============================] - 0s 4ms/step - loss: 424.8215 - val_loss: 397.8295
Epoch 8/32
51/51 [==============================] - 0s 3ms/step - loss: 390.9253 - val_loss: 398.1049
Epoch 9/32
51/51 [==============================] - 0s 4ms/step - loss: 347.3394 - val_loss: 400.3443
Epoch 10/32
51/51 [==============================] - 0s 3ms/step - loss: 302.2641 

#### Performing Inference

In [21]:
model.load_weights(output_path + '/weights.26.hdf5')

In [22]:
x_valid[42]

array([  9.32909,   0.     ,  18.1    ,   0.     ,   0.713  ,   6.185  ,
        98.7    ,   2.2616 ,  24.     , 666.     ,  20.2    , 396.9    ,
        18.13   ])

In [24]:
y_valid[42]

14.1

In [25]:
model.predict(np.reshape(x_valid[42], [1, 13]))

1/1 [==============================] - 0s 26ms/step


array([[14.703564]], dtype=float32)